server:
  port: 8080
  servlet:
    context-path: /api
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: root
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 10s
      letture:
        pool:
          max-active: 10
          max-wait: -1ms
          max-idle: 10
          min-time: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
sa-token:
  token-name: satoken
#  koken有效期
  timeout: 259200
  #最低活跃频率
  active-timeout: -1
  #是否允许同一账号多端登录
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true